version: '3.8'

services:
    # Serviço da aplicação Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: laravel
                uid: 1000
        image: facilita-teste
        container_name: facilita-teste-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - facilita-network

    # Servidor Nginx
    nginx:
        image: nginx:alpine
        container_name: facilita-teste-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - facilita-network
        depends_on:
            - app

    # Servidor de Banco de Dados (MySQL opcional)
    database:
        image: mysql:8.0
        container_name: facilita-teste-database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-facilita_teste}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_USER: ${DB_USERNAME:-laravel}
        ports:
            - 3306:3306
        volumes:
            - facilita-database:/var/lib/mysql
        networks:
            - facilita-network

# Configuração de redes
networks:
    facilita-network:
        driver: bridge

# Volumes para persistência de dados
volumes:
    facilita-database:
        driver: local
